# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0002_auto_20160409_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday_msg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
