# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0003_auto_20160409_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday_msg',
            field=models.CharField(default='', max_length=500),
        ),
    ]
