# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0004_auto_20160409_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
