# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0007_auto_20160409_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='send_msg',
            new_name='msg_active',
        ),
    ]
