# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0010_auto_20160410_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ssn',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='access_token',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expires_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 0, 56, 16, 935856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='refresh_token',
            field=models.CharField(default='', max_length=30),
        ),
    ]
