# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0012_auto_20160410_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ready_Message',
            new_name='ReadyMessage',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expires_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 5, 21, 32, 67436, tzinfo=utc)),
        ),
    ]
