# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0016_auto_20160411_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='message_time',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expires_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 19, 54, 6, 720161, tzinfo=utc)),
        ),
    ]
