# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes_app', '0017_auto_20160411_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='expires_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 2, 5, 7, 50, 478217, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='message_time',
            field=models.IntegerField(default=5),
        ),
    ]
